config/routes.rb
Rails.application.routes.draw do
  resources :stops
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
    root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :CategoryName, presence: true
  has_many :stops, dependent: :destroy
end

app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @stops = @category&.stop
  end

  # GET /categories/1 or /categories/1.json
  def show

  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find_by(params[:category_id])
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:CategoryName, :categories_path)
    end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: %i[ show edit update destroy ]

  # GET /stops or /stops.json
  def index
    @stops = Stop.all
    @categories = @stop&.category
  end

  # GET /stops/1 or /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = Stop.new
  end

  # GET /stops/1/edit
  def edit
  end

  # POST /stops or /stops.json
  def create
    @stop = Stop.new(stop_params)
    @category = Category.find_by(id: params[:category_id])

    respond_to do |format|
      if @stop.save
        format.html { redirect_to @stop, notice: "Stop was successfully created." }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1 or /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to @stop, notice: "Stop was successfully updated." }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1 or /stops/1.json
  def destroy
    @stop.destroy!

    respond_to do |format|
      format.html { redirect_to stops_path, status: :see_other, notice: "Stop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stop_params
      params.require(:stop).permit(:Stop_Name, :GPS_X, :GPS_Y, :Front_Of_Card, :Back_Of_Card, :Hidden_Card, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category:</strong>
    <%= category.CategoryName %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category&.errors&.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :CategoryName, style: "display: block" %>
    <%= form.text_field :CategoryName %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |

  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">

  <div>
    <label>
      <select onChange="if(this.selectedIndex!==0) self.location=this.options[this.selectedIndex].value">
        <option value="">Select a category</option>
        <% @categories.each do |category| %>
        <option value="<%= category_path(category) %>"><%= category.CategoryName %></option>
        <% end %>

      </select>
    </label>




  </div>









</div>

<%= link_to "New category", new_category_path %>

<!-- <div> -->

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<h2>Associated Stops</h2>
  <% if @category.stops.empty? %>
  <p> No stops available for this category.</p>
  <% else %>
  <ul>
    <% @category.stops.each do |category| %>
      <li><%= category.Stop_Name %></li>
    <% end %>
  </ul>
  <% end %>


<div>

  <%= link_to "Edit this category", edit_category_path %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CategoryWithStops</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stops/_form.html.erb
<%= form_with(model: stop) do |form| %>
  <% if stop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
        <% stop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Stop_Name, style: "display: block" %>
    <%= form.text_field :Stop_Name %>
  </div>

  <div>
    <%= form.label :GPS_X, style: "display: block" %>
    <%= form.text_field :GPS_X %>
  </div>

  <div>
    <%= form.label :GPS_Y, style: "display: block" %>
    <%= form.text_field :GPS_Y %>
  </div>

  <div>
    <%= form.label :Front_Of_Card, style: "display: block" %>
    <%= form.text_field :Front_Of_Card %>
  </div>

  <div>
    <%= form.label :Back_Of_Card, style: "display: block" %>
    <%= form.text_field :Back_Of_Card %>
  </div>

  <div>
    <%= form.label :Hidden_Card, style: "display: block" %>
    <%= form.text_field :Hidden_Card %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: dropdown" %>
  </div>


  <div>

    <%= form.select :category_id, Category.order(:CategoryName).map { |category | [category.CategoryName, category.id] },
                    { include_blank: true },
                    { class: "category" }%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stops/_stop.html.erb
<div id="<%= dom_id stop %>">
  <p>
    <strong>Stop name:</strong>
    <%= stop.Stop_Name %>
  </p>

  <p>
    <strong>Gps x:</strong>
    <%= stop.GPS_X %>
  </p>

  <p>
    <strong>Gps y:</strong>
    <%= stop.GPS_Y %>
  </p>

  <p>
    <strong>Front of card:</strong>
    <%= stop.Front_Of_Card %>
  </p>

  <p>
    <strong>Back of card:</strong>
    <%= stop.Back_Of_Card %>
  </p>

  <p>
    <strong>Hidden card:</strong>
    <%= stop.Hidden_Card %>
  </p>



</div>

app/views/stops/edit.html.erb
<h1>Editing stop</h1>

<%= render "form", stop: @stop %>

<br>

<div>
  <%= link_to "Show this stop", @stop %> |
  <%= link_to "Back to stops", stops_path %>
</div>

app/views/stops/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stops</h1>

<div id="stops">
  <% @stops.each do |stop| %>
    <%= render stop %>
    <p>
      <%= link_to "Show this stop", stop %>
    </p>
  <% end %>
</div>

<%= link_to "New stop", new_stop_path %>

app/views/stops/new.html.erb
<h1>New stop</h1>

<%= render "form", stop: @stop %>

<br>

<div>
  <%= link_to "Back to stops", stops_path %>
</div>

app/views/stops/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @stop %>

<div>
  <%= link_to "Edit this stop", edit_stop_path(@stop) %> |
  <%= link_to "Back to stops", stops_path %>

  <%= button_to "Destroy this stop", @stop, method: :delete %>
</div>